---
command: >
  /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java
  -jar
  /Users/tn6091/opt/google-java-format/google-java-format-1.15.0-all-deps.jar
  --skip-javadoc-formatting --replace
num_spaces: 2
directories:
  - one
  - two
num_processes: 4
extension: java
multiline_comment_char: "*"
