---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix', 'lf']
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/toddnguyen47/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: prettify-json
        args: ["--indent", "2"] # defaults to indenting with 2 spaces
        types: ["json"]
      - id: convert-beginning-tabs
        # --tab-size defaults to 4 with no args
        args: ["--tab-size", "4"]
        types: ["java"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.6
    hooks:
      # Run the formatter.
      - id: ruff-format
        types: ["python"]
      # Run the linter.
      - id: ruff
        types: ["python"]
