[package]
authors = ["zx"]
edition = "2018"
name = "pass-in-impl-trait-as-func-parameter"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pretty_assertions = "0.7"
